export const starterTests = [
  { name: 'Escala Wechsler de Inteligência para Adultos', acronym: 'WAIS-III', category: 'Inteligência', source: 'SATEPSI', ageRange: '16 a 89 anos', minutes: 90 },
  { name: 'Escala Wechsler de Inteligência para Crianças', acronym: 'WISC-IV', category: 'Inteligência', source: 'SATEPSI', ageRange: '6 a 16 anos', minutes: 90 },
  { name: 'Teste de Atenção Concentrada', acronym: 'TEACO-FF', category: 'Atenção', source: 'SATEPSI', ageRange: 'Adultos', minutes: 15 },
  { name: 'Teste de Atenção Dividida', acronym: 'TEADI', category: 'Atenção', source: 'SATEPSI', ageRange: 'Adultos', minutes: 20 },
  { name: 'Teste de Atenção Alternada', acronym: 'TEALT', category: 'Atenção', source: 'SATEPSI', ageRange: 'Adultos', minutes: 20 },
  { name: 'Bateria Psicológica para Avaliação da Atenção', acronym: 'BPA', category: 'Atenção', source: 'SATEPSI', ageRange: 'Crianças e adultos', minutes: 40 },
  { name: 'Teste dos Cinco Dígitos', acronym: 'FDT', category: 'Funções executivas', source: 'SATEPSI', ageRange: '6 a 92 anos', minutes: 15 },
  { name: 'Teste de Aprendizagem Auditivo-Verbal de Rey', acronym: 'RAVLT', category: 'Memória', source: 'Complementar', ageRange: 'Crianças, adultos e idosos', minutes: 30 },
  { name: 'Figura Complexa de Rey', acronym: 'FCR', category: 'Memória e visuoconstrução', source: 'SATEPSI', ageRange: '4 anos ou mais', minutes: 30 },
  { name: 'Teste de Trilhas Coloridas', acronym: 'CTT', category: 'Atenção e flexibilidade', source: 'SATEPSI', ageRange: 'Crianças e adultos', minutes: 20 },
  { name: 'Teste de Fluência Verbal', acronym: 'FAS/Semântica', category: 'Linguagem e funções executivas', source: 'Complementar', ageRange: 'Crianças e adultos', minutes: 10 },
  { name: 'Teste de Nomeação de Boston', acronym: 'BNT', category: 'Linguagem', source: 'Complementar', ageRange: 'Adultos e idosos', minutes: 25 },
  { name: 'Escala de Inteligência Wechsler Abreviada', acronym: 'WASI', category: 'Inteligência', source: 'SATEPSI', ageRange: '6 a 89 anos', minutes: 45 },
  { name: 'Bateria de Provas de Raciocínio', acronym: 'BPR-5', category: 'Raciocínio', source: 'SATEPSI', ageRange: 'Adolescentes e adultos', minutes: 60 },
  { name: 'Escala de Maturidade Mental Columbia', acronym: 'CMMS', category: 'Raciocínio não verbal', source: 'SATEPSI', ageRange: '3 a 9 anos', minutes: 30 },
  { name: 'Teste de Desempenho Escolar', acronym: 'TDE-II', category: 'Desempenho acadêmico', source: 'SATEPSI', ageRange: 'Escolares', minutes: 60 },
  { name: 'Teste de Aprendizagem e Memória Infantil', acronym: 'TAM-I', category: 'Memória', source: 'SATEPSI', ageRange: 'Crianças', minutes: 40 },
  { name: 'Inventário de Funções Executivas e Regulação Infantil', acronym: 'IFERA-I', category: 'Funções executivas', source: 'SATEPSI', ageRange: 'Crianças', minutes: 20 },
  { name: 'Child Behavior Checklist', acronym: 'CBCL', category: 'Comportamento', source: 'Complementar', ageRange: '1,5 a 18 anos', minutes: 20 },
  { name: 'Escala de Responsividade Social', acronym: 'SRS-2', category: 'Cognição social', source: 'SATEPSI', ageRange: '2,5 anos ou mais', minutes: 20 },
  { name: 'Escala de TDAH para Adultos', acronym: 'ETDAH-AD', category: 'Sintomas de TDAH', source: 'SATEPSI', ageRange: 'Adultos', minutes: 20 },
  { name: 'Inventário de Depressão de Beck', acronym: 'BDI-II', category: 'Humor', source: 'SATEPSI', ageRange: 'Adolescentes e adultos', minutes: 15 },
  { name: 'Inventário de Ansiedade de Beck', acronym: 'BAI', category: 'Ansiedade', source: 'SATEPSI', ageRange: 'Adolescentes e adultos', minutes: 15 },
  { name: 'Montreal Cognitive Assessment', acronym: 'MoCA', category: 'Rastreio cognitivo', source: 'Complementar', ageRange: 'Adultos e idosos', minutes: 15 },
  { name: 'Mini Exame do Estado Mental', acronym: 'MEEM', category: 'Rastreio cognitivo', source: 'Complementar', ageRange: 'Adultos e idosos', minutes: 15 },
] as const
