/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FTokenRouteImport } from './routes/f.$token'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSupervisionRouteImport } from './routes/_authenticated/supervision'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedMaterialsRouteImport } from './routes/_authenticated/materials'
import { Route as AuthenticatedListaEsperaRouteImport } from './routes/_authenticated/lista-espera'
import { Route as AuthenticatedKanbanRouteImport } from './routes/_authenticated/kanban'
import { Route as AuthenticatedFormulariosRouteImport } from './routes/_authenticated/formularios'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCatalogRouteImport } from './routes/_authenticated/catalog'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedPatientsIndexRouteImport } from './routes/_authenticated/patients.index'
import { Route as AuthenticatedPatientsIdIndexRouteImport } from './routes/_authenticated/patients.$id.index'
import { Route as ApiPublicFormsTokenRouteImport } from './routes/api/public/forms.$token'
import { Route as AuthenticatedPatientsIdTriagemRouteImport } from './routes/_authenticated/patients.$id.triagem'
import { Route as AuthenticatedPatientsIdLaudoRouteImport } from './routes/_authenticated/patients.$id.laudo'
import { Route as AuthenticatedPatientsIdAnamneseRouteImport } from './routes/_authenticated/patients.$id.anamnese'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FTokenRoute = FTokenRouteImport.update({
  id: '/f/$token',
  path: '/f/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupervisionRoute =
  AuthenticatedSupervisionRouteImport.update({
    id: '/supervision',
    path: '/supervision',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaterialsRoute = AuthenticatedMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListaEsperaRoute =
  AuthenticatedListaEsperaRouteImport.update({
    id: '/lista-espera',
    path: '/lista-espera',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKanbanRoute = AuthenticatedKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFormulariosRoute =
  AuthenticatedFormulariosRouteImport.update({
    id: '/formularios',
    path: '/formularios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCatalogRoute = AuthenticatedCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatientsIndexRoute =
  AuthenticatedPatientsIndexRouteImport.update({
    id: '/patients/',
    path: '/patients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientsIdIndexRoute =
  AuthenticatedPatientsIdIndexRouteImport.update({
    id: '/patients/$id/',
    path: '/patients/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicFormsTokenRoute = ApiPublicFormsTokenRouteImport.update({
  id: '/api/public/forms/$token',
  path: '/api/public/forms/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPatientsIdTriagemRoute =
  AuthenticatedPatientsIdTriagemRouteImport.update({
    id: '/patients/$id/triagem',
    path: '/patients/$id/triagem',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientsIdLaudoRoute =
  AuthenticatedPatientsIdLaudoRouteImport.update({
    id: '/patients/$id/laudo',
    path: '/patients/$id/laudo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientsIdAnamneseRoute =
  AuthenticatedPatientsIdAnamneseRouteImport.update({
    id: '/patients/$id/anamnese',
    path: '/patients/$id/anamnese',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/formularios': typeof AuthenticatedFormulariosRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/lista-espera': typeof AuthenticatedListaEsperaRoute
  '/materials': typeof AuthenticatedMaterialsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/supervision': typeof AuthenticatedSupervisionRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/f/$token': typeof FTokenRoute
  '/patients/': typeof AuthenticatedPatientsIndexRoute
  '/patients/$id/anamnese': typeof AuthenticatedPatientsIdAnamneseRoute
  '/patients/$id/laudo': typeof AuthenticatedPatientsIdLaudoRoute
  '/patients/$id/triagem': typeof AuthenticatedPatientsIdTriagemRoute
  '/api/public/forms/$token': typeof ApiPublicFormsTokenRoute
  '/patients/$id/': typeof AuthenticatedPatientsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/formularios': typeof AuthenticatedFormulariosRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/lista-espera': typeof AuthenticatedListaEsperaRoute
  '/materials': typeof AuthenticatedMaterialsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/supervision': typeof AuthenticatedSupervisionRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/f/$token': typeof FTokenRoute
  '/patients': typeof AuthenticatedPatientsIndexRoute
  '/patients/$id/anamnese': typeof AuthenticatedPatientsIdAnamneseRoute
  '/patients/$id/laudo': typeof AuthenticatedPatientsIdLaudoRoute
  '/patients/$id/triagem': typeof AuthenticatedPatientsIdTriagemRoute
  '/api/public/forms/$token': typeof ApiPublicFormsTokenRoute
  '/patients/$id': typeof AuthenticatedPatientsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/catalog': typeof AuthenticatedCatalogRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/formularios': typeof AuthenticatedFormulariosRoute
  '/_authenticated/kanban': typeof AuthenticatedKanbanRoute
  '/_authenticated/lista-espera': typeof AuthenticatedListaEsperaRoute
  '/_authenticated/materials': typeof AuthenticatedMaterialsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/supervision': typeof AuthenticatedSupervisionRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/f/$token': typeof FTokenRoute
  '/_authenticated/patients/': typeof AuthenticatedPatientsIndexRoute
  '/_authenticated/patients/$id/anamnese': typeof AuthenticatedPatientsIdAnamneseRoute
  '/_authenticated/patients/$id/laudo': typeof AuthenticatedPatientsIdLaudoRoute
  '/_authenticated/patients/$id/triagem': typeof AuthenticatedPatientsIdTriagemRoute
  '/api/public/forms/$token': typeof ApiPublicFormsTokenRoute
  '/_authenticated/patients/$id/': typeof AuthenticatedPatientsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agenda'
    | '/catalog'
    | '/dashboard'
    | '/financeiro'
    | '/formularios'
    | '/kanban'
    | '/lista-espera'
    | '/materials'
    | '/reports'
    | '/settings'
    | '/supervision'
    | '/tasks'
    | '/f/$token'
    | '/patients/'
    | '/patients/$id/anamnese'
    | '/patients/$id/laudo'
    | '/patients/$id/triagem'
    | '/api/public/forms/$token'
    | '/patients/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agenda'
    | '/catalog'
    | '/dashboard'
    | '/financeiro'
    | '/formularios'
    | '/kanban'
    | '/lista-espera'
    | '/materials'
    | '/reports'
    | '/settings'
    | '/supervision'
    | '/tasks'
    | '/f/$token'
    | '/patients'
    | '/patients/$id/anamnese'
    | '/patients/$id/laudo'
    | '/patients/$id/triagem'
    | '/api/public/forms/$token'
    | '/patients/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agenda'
    | '/_authenticated/catalog'
    | '/_authenticated/dashboard'
    | '/_authenticated/financeiro'
    | '/_authenticated/formularios'
    | '/_authenticated/kanban'
    | '/_authenticated/lista-espera'
    | '/_authenticated/materials'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/supervision'
    | '/_authenticated/tasks'
    | '/f/$token'
    | '/_authenticated/patients/'
    | '/_authenticated/patients/$id/anamnese'
    | '/_authenticated/patients/$id/laudo'
    | '/_authenticated/patients/$id/triagem'
    | '/api/public/forms/$token'
    | '/_authenticated/patients/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FTokenRoute: typeof FTokenRoute
  ApiPublicFormsTokenRoute: typeof ApiPublicFormsTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$token': {
      id: '/f/$token'
      path: '/f/$token'
      fullPath: '/f/$token'
      preLoaderRoute: typeof FTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supervision': {
      id: '/_authenticated/supervision'
      path: '/supervision'
      fullPath: '/supervision'
      preLoaderRoute: typeof AuthenticatedSupervisionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/materials': {
      id: '/_authenticated/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof AuthenticatedMaterialsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lista-espera': {
      id: '/_authenticated/lista-espera'
      path: '/lista-espera'
      fullPath: '/lista-espera'
      preLoaderRoute: typeof AuthenticatedListaEsperaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kanban': {
      id: '/_authenticated/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AuthenticatedKanbanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/formularios': {
      id: '/_authenticated/formularios'
      path: '/formularios'
      fullPath: '/formularios'
      preLoaderRoute: typeof AuthenticatedFormulariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog': {
      id: '/_authenticated/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AuthenticatedCatalogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients/': {
      id: '/_authenticated/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof AuthenticatedPatientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients/$id/': {
      id: '/_authenticated/patients/$id/'
      path: '/patients/$id'
      fullPath: '/patients/$id/'
      preLoaderRoute: typeof AuthenticatedPatientsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/forms/$token': {
      id: '/api/public/forms/$token'
      path: '/api/public/forms/$token'
      fullPath: '/api/public/forms/$token'
      preLoaderRoute: typeof ApiPublicFormsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/patients/$id/triagem': {
      id: '/_authenticated/patients/$id/triagem'
      path: '/patients/$id/triagem'
      fullPath: '/patients/$id/triagem'
      preLoaderRoute: typeof AuthenticatedPatientsIdTriagemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients/$id/laudo': {
      id: '/_authenticated/patients/$id/laudo'
      path: '/patients/$id/laudo'
      fullPath: '/patients/$id/laudo'
      preLoaderRoute: typeof AuthenticatedPatientsIdLaudoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients/$id/anamnese': {
      id: '/_authenticated/patients/$id/anamnese'
      path: '/patients/$id/anamnese'
      fullPath: '/patients/$id/anamnese'
      preLoaderRoute: typeof AuthenticatedPatientsIdAnamneseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedCatalogRoute: typeof AuthenticatedCatalogRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedFormulariosRoute: typeof AuthenticatedFormulariosRoute
  AuthenticatedKanbanRoute: typeof AuthenticatedKanbanRoute
  AuthenticatedListaEsperaRoute: typeof AuthenticatedListaEsperaRoute
  AuthenticatedMaterialsRoute: typeof AuthenticatedMaterialsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSupervisionRoute: typeof AuthenticatedSupervisionRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedPatientsIndexRoute: typeof AuthenticatedPatientsIndexRoute
  AuthenticatedPatientsIdAnamneseRoute: typeof AuthenticatedPatientsIdAnamneseRoute
  AuthenticatedPatientsIdLaudoRoute: typeof AuthenticatedPatientsIdLaudoRoute
  AuthenticatedPatientsIdTriagemRoute: typeof AuthenticatedPatientsIdTriagemRoute
  AuthenticatedPatientsIdIndexRoute: typeof AuthenticatedPatientsIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedCatalogRoute: AuthenticatedCatalogRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedFormulariosRoute: AuthenticatedFormulariosRoute,
  AuthenticatedKanbanRoute: AuthenticatedKanbanRoute,
  AuthenticatedListaEsperaRoute: AuthenticatedListaEsperaRoute,
  AuthenticatedMaterialsRoute: AuthenticatedMaterialsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSupervisionRoute: AuthenticatedSupervisionRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedPatientsIndexRoute: AuthenticatedPatientsIndexRoute,
  AuthenticatedPatientsIdAnamneseRoute: AuthenticatedPatientsIdAnamneseRoute,
  AuthenticatedPatientsIdLaudoRoute: AuthenticatedPatientsIdLaudoRoute,
  AuthenticatedPatientsIdTriagemRoute: AuthenticatedPatientsIdTriagemRoute,
  AuthenticatedPatientsIdIndexRoute: AuthenticatedPatientsIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FTokenRoute: FTokenRoute,
  ApiPublicFormsTokenRoute: ApiPublicFormsTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
