
ALTER TABLE public.test_catalog
  ADD CONSTRAINT test_catalog_acronym_key UNIQUE (acronym);

INSERT INTO public.test_catalog (name, acronym, category, source, status, age_range, application_mode, estimated_minutes, notes)
VALUES
  ('Escala Wechsler de Inteligência para Adultos - 4ª ed.', 'WAIS-IV', 'Inteligência', 'SATEPSI', 'active', '16 a 90 anos', 'Individual presencial', 90, 'Padrão-ouro para avaliação intelectual em adultos.'),
  ('Escala Wechsler de Inteligência para Crianças - 5ª ed.', 'WISC-V', 'Inteligência', 'SATEPSI', 'active', '6 a 16 anos', 'Individual presencial', 90, 'Versão mais recente da WISC no Brasil.'),
  ('Escala Wechsler de Inteligência Pré-Escolar', 'WPPSI-IV', 'Inteligência', 'SATEPSI', 'active', '2:6 a 7:7 anos', 'Individual presencial', 60, 'Avaliação intelectual pré-escolar.'),
  ('Escala Wechsler Não Verbal de Inteligência', 'WNV', 'Inteligência', 'SATEPSI', 'active', '4 a 21 anos', 'Individual presencial', 45, 'Instrumento não verbal para populações especiais.'),
  ('Matrizes Progressivas de Raven - Geral', 'Raven Geral', 'Inteligência', 'SATEPSI', 'active', 'Adultos', 'Individual/coletivo', 45, 'Inteligência não-verbal.'),
  ('Matrizes Progressivas Coloridas de Raven', 'Raven Colorido', 'Inteligência', 'SATEPSI', 'active', '5 a 11 anos', 'Individual/coletivo', 30, 'Versão infantil das matrizes de Raven.'),
  ('Matrizes Progressivas Avançadas de Raven', 'Raven Avançado', 'Inteligência', 'SATEPSI', 'active', 'Adultos com alto QI', 'Individual/coletivo', 60, 'Discrimina habilidades superiores.'),
  ('Escala de Inteligência Stanford-Binet', 'SB-5', 'Inteligência', 'Complementar', 'active', '2 a 85+ anos', 'Individual presencial', 60, 'Instrumento internacional.'),
  ('Teste Não Verbal de Inteligência Geral', 'BETA-III', 'Inteligência', 'SATEPSI', 'active', '16 anos ou mais', 'Individual/coletivo', 30, 'Inteligência não-verbal em adultos.'),
  ('Teste de Atenção por Cancelamento', 'TAC', 'Atenção', 'SATEPSI', 'active', 'Crianças e adultos', 'Individual', 15, 'Atenção sustentada e seletiva.'),
  ('Teste D2 - Atenção Concentrada', 'D2-R', 'Atenção', 'SATEPSI', 'active', '9 a 60 anos', 'Individual/coletivo', 10, 'Atenção seletiva e concentração.'),
  ('Teste de Trilhas - Parte A e B', 'TMT', 'Atenção e flexibilidade', 'Complementar', 'active', 'Adultos e idosos', 'Individual', 10, 'Atenção sustentada e flexibilidade cognitiva.'),
  ('Continuous Performance Test', 'CPT-3', 'Atenção', 'Complementar', 'active', '8 anos ou mais', 'Individual computadorizado', 20, 'Atenção sustentada e impulsividade.'),
  ('Teste de Atenção Visual', 'TAVIS-4', 'Atenção', 'SATEPSI', 'active', '6 a 11 anos', 'Individual computadorizado', 20, 'Atenção seletiva, alternada e sustentada infantil.'),
  ('Teste de Cancelamento de Sinos', 'Bells Test', 'Atenção', 'Complementar', 'active', 'Adultos', 'Individual', 5, 'Rastreio de negligência visuoespacial.'),
  ('Wisconsin Card Sorting Test', 'WCST', 'Funções executivas', 'Complementar', 'active', '6:5 a 89 anos', 'Individual', 30, 'Flexibilidade cognitiva e formação de conceitos.'),
  ('Torre de Londres', 'TOL-DX', 'Funções executivas', 'Complementar', 'active', '7 a 80 anos', 'Individual', 20, 'Planejamento e resolução de problemas.'),
  ('Torre de Hanói', 'Hanoi', 'Funções executivas', 'Complementar', 'active', '6 anos ou mais', 'Individual', 15, 'Planejamento sequencial.'),
  ('Teste Stroop de Cores e Palavras', 'Stroop', 'Funções executivas', 'Complementar', 'active', '7 anos ou mais', 'Individual', 10, 'Controle inibitório e atenção seletiva.'),
  ('Teste Hayling', 'Hayling', 'Funções executivas', 'Complementar', 'active', 'Adultos', 'Individual', 10, 'Controle inibitório e iniciação.'),
  ('Teste Brixton', 'Brixton', 'Funções executivas', 'Complementar', 'active', 'Adultos', 'Individual', 10, 'Detecção de regras e flexibilidade.'),
  ('Behavioral Assessment of the Dysexecutive Syndrome', 'BADS', 'Funções executivas', 'Complementar', 'active', '16 a 87 anos', 'Individual', 40, 'Bateria ecológica de disfunção executiva.'),
  ('Iowa Gambling Task', 'IGT', 'Funções executivas', 'Complementar', 'active', 'Adolescentes e adultos', 'Individual computadorizado', 20, 'Tomada de decisão sob risco.'),
  ('Inventário de Comportamento Executivo', 'BRIEF-2', 'Funções executivas', 'Complementar', 'active', '5 a 18 anos', 'Questionário', 15, 'Funções executivas no cotidiano infantil.'),
  ('Escala Wechsler de Memória', 'WMS-IV', 'Memória', 'Complementar', 'active', '16 a 90 anos', 'Individual', 90, 'Bateria completa de memória em adultos.'),
  ('Teste de Aprendizagem Verbal da Califórnia', 'CVLT-II', 'Memória', 'Complementar', 'active', '16 a 89 anos', 'Individual', 40, 'Memória verbal episódica.'),
  ('Rivermead Behavioural Memory Test', 'RBMT-3', 'Memória', 'Complementar', 'active', '16 a 89 anos', 'Individual', 30, 'Memória ecológica cotidiana.'),
  ('Teste Pictórico de Memória', 'TEPIC-M', 'Memória', 'SATEPSI', 'active', 'Adultos', 'Individual', 15, 'Memória visual de curto e longo prazo.'),
  ('Teste de Memória Visual de Reconhecimento', 'MEVIR', 'Memória', 'SATEPSI', 'active', 'Adultos', 'Individual', 10, 'Reconhecimento visual de figuras.'),
  ('Teste de Aprendizagem Auditivo-Verbal de Rey - Infantil', 'RAVLT-I', 'Memória', 'Complementar', 'active', 'Crianças', 'Individual', 30, 'Adaptação infantil do RAVLT.'),
  ('Span de Dígitos', 'Span Dígitos', 'Memória', 'Complementar', 'active', 'Todas as idades', 'Individual', 5, 'Memória de trabalho verbal.'),
  ('Corsi Block-Tapping', 'Corsi', 'Memória', 'Complementar', 'active', 'Todas as idades', 'Individual', 10, 'Memória de trabalho visuoespacial.'),
  ('Bateria Montreal de Avaliação da Comunicação', 'MAC-BR', 'Linguagem', 'Complementar', 'active', 'Adultos', 'Individual', 90, 'Comunicação em lesados de hemisfério direito.'),
  ('Teste de Vocabulário por Imagens Peabody', 'TVIP', 'Linguagem', 'SATEPSI', 'active', '2:6 a 18 anos', 'Individual', 15, 'Vocabulário receptivo.'),
  ('Prova de Consciência Fonológica', 'PCF', 'Linguagem', 'Complementar', 'active', 'Escolares', 'Individual', 20, 'Habilidades metafonológicas.'),
  ('Bateria Boston de Diagnóstico das Afasias', 'BDAE', 'Linguagem', 'Complementar', 'active', 'Adultos', 'Individual', 90, 'Diagnóstico e classificação de afasias.'),
  ('Token Test', 'Token Test', 'Linguagem', 'Complementar', 'active', 'Crianças e adultos', 'Individual', 10, 'Compreensão auditiva de instruções.'),
  ('Teste Gestáltico Visomotor de Bender - SPG', 'Bender-SPG', 'Visuoconstrução', 'SATEPSI', 'active', '6 a 10 anos', 'Individual', 15, 'Maturação visomotora infantil.'),
  ('Teste Gestáltico Visomotor de Bender - Koppitz', 'Bender-Koppitz-2', 'Visuoconstrução', 'SATEPSI', 'active', '5 a 12 anos', 'Individual', 15, 'Maturação perceptomotora.'),
  ('Teste de Percepção Visual sem Motor', 'MVPT-4', 'Percepção visual', 'Complementar', 'active', '4 a 80 anos', 'Individual', 25, 'Percepção visual sem componente motor.'),
  ('Teste de Habilidades Visuoperceptivas', 'DTVP-3', 'Percepção visual', 'Complementar', 'active', '4 a 12 anos', 'Individual', 30, 'Percepção visual e integração visomotora.'),
  ('Teste de Competência de Leitura de Palavras e Pseudopalavras', 'TCLPP', 'Desempenho acadêmico', 'SATEPSI', 'active', 'Escolares', 'Individual/coletivo', 20, 'Habilidades de leitura.'),
  ('Prova de Aritmética', 'Aritmética', 'Desempenho acadêmico', 'Complementar', 'active', 'Escolares', 'Individual', 20, 'Habilidades matemáticas escolares.'),
  ('Avaliação da Compreensão Leitora de Textos Expositivos', 'ACLTE', 'Desempenho acadêmico', 'SATEPSI', 'active', 'Ensino fundamental', 'Individual/coletivo', 30, 'Compreensão de textos.'),
  ('Inventário de Depressão Infantil', 'CDI', 'Humor', 'SATEPSI', 'active', '7 a 17 anos', 'Individual/questionário', 15, 'Sintomas depressivos em crianças e adolescentes.'),
  ('Escala Hamilton de Depressão', 'HAM-D', 'Humor', 'Complementar', 'active', 'Adultos', 'Entrevista', 20, 'Gravidade de sintomas depressivos.'),
  ('Escala Hamilton de Ansiedade', 'HAM-A', 'Ansiedade', 'Complementar', 'active', 'Adultos', 'Entrevista', 20, 'Gravidade de sintomas ansiosos.'),
  ('Inventário de Ansiedade Traço-Estado', 'IDATE', 'Ansiedade', 'Complementar', 'active', 'Adolescentes e adultos', 'Questionário', 15, 'Ansiedade traço e estado.'),
  ('Escala de Estresse Percebido', 'PSS', 'Estresse', 'Complementar', 'active', 'Adultos', 'Questionário', 10, 'Percepção de estresse cotidiano.'),
  ('Inventário Fatorial de Personalidade', 'IFP-II', 'Personalidade', 'SATEPSI', 'active', '16 anos ou mais', 'Questionário', 60, 'Traços de personalidade.'),
  ('Bateria Fatorial de Personalidade', 'BFP', 'Personalidade', 'SATEPSI', 'active', '18 a 60 anos', 'Questionário', 40, 'Big Five brasileiro.'),
  ('Teste de Rorschach - Sistema R-PAS', 'Rorschach R-PAS', 'Personalidade', 'SATEPSI', 'active', 'Crianças e adultos', 'Individual', 90, 'Avaliação projetiva de personalidade.'),
  ('Teste de Apercepção Temática', 'TAT', 'Personalidade', 'Complementar', 'active', 'Adolescentes e adultos', 'Individual', 60, 'Teste projetivo temático.'),
  ('Teste das Pirâmides Coloridas de Pfister', 'Pfister', 'Personalidade', 'SATEPSI', 'active', '5 anos ou mais', 'Individual', 30, 'Avaliação afetivo-emocional.'),
  ('Teste da Casa-Árvore-Pessoa', 'HTP', 'Personalidade', 'SATEPSI', 'active', '4 anos ou mais', 'Individual', 30, 'Teste projetivo gráfico.'),
  ('Desenho da Figura Humana - Sisto', 'DFH-Sisto', 'Personalidade', 'SATEPSI', 'active', '5 a 15 anos', 'Individual', 15, 'Avaliação cognitiva e emocional infantil.'),
  ('Escalas de Avaliação de TDAH - Conners 3', 'Conners 3', 'Sintomas de TDAH', 'Complementar', 'active', '6 a 18 anos', 'Questionário', 20, 'Sintomas de TDAH em crianças e adolescentes.'),
  ('SNAP-IV', 'SNAP-IV', 'Sintomas de TDAH', 'Complementar', 'active', 'Crianças e adolescentes', 'Questionário', 10, 'Rastreio de TDAH e transtorno opositor.'),
  ('Escala Wender-Utah para TDAH em Adultos', 'WURS', 'Sintomas de TDAH', 'Complementar', 'active', 'Adultos', 'Questionário', 15, 'Avaliação retrospectiva de TDAH.'),
  ('Adult Self-Report Scale', 'ASRS-18', 'Sintomas de TDAH', 'Complementar', 'active', 'Adultos', 'Autorrelato', 5, 'Rastreio de TDAH adulto (OMS).'),
  ('Youth Self-Report', 'YSR', 'Comportamento', 'Complementar', 'active', '11 a 18 anos', 'Autorrelato', 20, 'Complementa a CBCL na perspectiva do adolescente.'),
  ('Teacher Report Form', 'TRF', 'Comportamento', 'Complementar', 'active', '6 a 18 anos', 'Questionário para professores', 20, 'Perspectiva escolar do comportamento infantil.'),
  ('Strengths and Difficulties Questionnaire', 'SDQ', 'Comportamento', 'Complementar', 'active', '4 a 17 anos', 'Questionário', 10, 'Rastreio de saúde mental infantil.'),
  ('Autism Diagnostic Observation Schedule', 'ADOS-2', 'Cognição social', 'Complementar', 'active', '12 meses ou mais', 'Individual observacional', 60, 'Padrão-ouro no diagnóstico de TEA.'),
  ('Autism Diagnostic Interview - Revised', 'ADI-R', 'Cognição social', 'Complementar', 'active', '2 anos ou mais (idade mental)', 'Entrevista com cuidadores', 120, 'Diagnóstico de TEA por entrevista.'),
  ('Childhood Autism Rating Scale', 'CARS-2', 'Cognição social', 'Complementar', 'active', '2 anos ou mais', 'Escala observacional', 30, 'Gravidade de sintomas de TEA.'),
  ('Modified Checklist for Autism in Toddlers', 'M-CHAT-R/F', 'Cognição social', 'Complementar', 'active', '16 a 30 meses', 'Questionário', 5, 'Rastreio precoce de TEA.'),
  ('Addenbrooke Cognitive Examination - Revised', 'ACE-R', 'Rastreio cognitivo', 'Complementar', 'active', 'Idosos', 'Individual', 20, 'Rastreio de demência.'),
  ('Escala de Avaliação Clínica da Demência', 'CDR', 'Demência', 'Complementar', 'active', 'Idosos', 'Entrevista', 40, 'Estadiamento de demência.'),
  ('Bateria Breve de Rastreio Cognitivo', 'BBRC', 'Rastreio cognitivo', 'Complementar', 'active', 'Idosos', 'Individual', 15, 'Rastreio adaptado à população brasileira.'),
  ('Escala de Depressão Geriátrica', 'GDS-15', 'Humor', 'Complementar', 'active', 'Idosos', 'Autorrelato', 5, 'Sintomas depressivos em idosos.'),
  ('Inventário Neuropsiquiátrico', 'NPI', 'Comportamento', 'Complementar', 'active', 'Idosos', 'Entrevista com cuidadores', 20, 'Sintomas neuropsiquiátricos em demências.'),
  ('Escala de Atividades Instrumentais de Lawton', 'Lawton AIVD', 'Funcionalidade', 'Complementar', 'active', 'Idosos', 'Entrevista', 10, 'Avaliação funcional de atividades instrumentais.'),
  ('Índice de Barthel', 'Barthel', 'Funcionalidade', 'Complementar', 'active', 'Adultos e idosos', 'Entrevista', 10, 'Avaliação funcional de atividades básicas.'),
  ('Escala Bayley de Desenvolvimento Infantil', 'Bayley-III', 'Desenvolvimento infantil', 'Complementar', 'active', '1 a 42 meses', 'Individual', 60, 'Desenvolvimento cognitivo, motor e linguístico.'),
  ('Denver-II', 'Denver-II', 'Desenvolvimento infantil', 'Complementar', 'active', '0 a 6 anos', 'Individual', 30, 'Rastreio do desenvolvimento infantil.'),
  ('Escala de Desenvolvimento Motor', 'EDM', 'Desenvolvimento motor', 'SATEPSI', 'active', '2 a 11 anos', 'Individual', 30, 'Desenvolvimento motor infantil.'),
  ('Perfil Sensorial 2', 'PS-2', 'Processamento sensorial', 'Complementar', 'active', '0 a 14 anos', 'Questionário', 15, 'Processamento sensorial infantil.'),
  ('Sistema de Avaliação de Habilidades Sociais', 'SSRS-BR', 'Habilidades sociais', 'SATEPSI', 'active', 'Escolares', 'Questionário', 20, 'Habilidades sociais em crianças.'),
  ('Reading the Mind in the Eyes Test', 'RMET', 'Cognição social', 'Complementar', 'active', 'Adolescentes e adultos', 'Individual', 15, 'Teoria da mente e reconhecimento emocional.'),
  ('Teste de Reconhecimento de Expressões Faciais', 'TREF', 'Cognição social', 'Complementar', 'active', 'Crianças e adultos', 'Individual', 15, 'Reconhecimento de emoções faciais básicas.'),
  ('WHOQOL-BREF', 'WHOQOL-BREF', 'Qualidade de vida', 'Complementar', 'active', 'Adultos', 'Autorrelato', 15, 'Qualidade de vida (OMS).'),
  ('Mini International Neuropsychiatric Interview', 'MINI', 'Rastreio psiquiátrico', 'Complementar', 'active', 'Adultos', 'Entrevista estruturada', 30, 'Rastreio de transtornos psiquiátricos DSM/CID.')
ON CONFLICT (acronym) DO NOTHING;
