DELETE FROM public.standard_battery;
INSERT INTO public.standard_battery (name, acronym, category) VALUES
('Wechsler Adult Intelligence Scale - III', 'WAIS-III', 'Inteligência'),
('Advanced Progressive Matrices RAVEN', 'APM RAVEN', 'Inteligência'),
('Test of Attention D2-R', 'D2-R', 'Atenção'),
('Continuous Performance Test - FLEX', 'CPT-FLEX', 'Atenção'),
('Bateria Psicológica para Avaliação da Atenção-2', 'BPA-2', 'Atenção'),
('Torre de Londres', 'TORRE DE LONDRES', 'Funções Executivas'),
('Escala de Transtorno do Déficit de Atenção / Hiperatividade', 'ETDAH-AD', 'TDAH'),
('Executive Function Index', 'BDEFS', 'Funções Executivas'),
('Escala de Prejuízo Funcional TDAH', 'EPF-TDAH', 'TDAH'),
('Social Responsiveness Scale - 2', 'SRS-2', 'Autismo'),
('Emotion Recognition Assessment - Facial', 'ERA-F', 'Social'),
('Camouflaging Autistic Traits Questionnaire', 'CAT-Q', 'Autismo'),
('Autism Spectrum Quotient', 'AQ', 'Autismo'),
('Empathy Quotient', 'EQ', 'Social'),
('Ritvo Autism Asperger Diagnostic Scale', 'RAADS', 'Autismo'),
('Rey Auditory Verbal Learning Test', 'RAVLT', 'Memória'),
('Teste de Memória de Reconhecimento - 2', 'TEM-R-2', 'Memória'),
('Five Digit Test', 'FDT', 'Funções Executivas'),
('Matching Familiar Figures Test', 'MFFT', 'Impulsividade'),
('Bateria Fatorial de Personalidade', 'BFP', 'Personalidade'),
('Teste de Pfister', 'PFISTER', 'Personalidade'),
('House-Tree-Person', 'HTP', 'Personalidade'),
('Escala de Humor', 'HUMOR-A', 'Humor'),
('Beck Depression Inventory - II', 'BDI-II', 'Humor'),
('Escala de Ansiedade Generalizada', 'EAG-A', 'Ansiedade'),
('Beck Anxiety Inventory', 'BAI', 'Ansiedade'),
('Inventário de Habilidades Sociais - 2', 'IHS-2', 'Social');
